//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlastairLundy.Extensions.IO.Internal.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlastairLundy.Extensions.IO.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find directory with file path of {x}..
        /// </summary>
        internal static string Exceptions_IO_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Exceptions_IO_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find file with file path of {x}..
        /// </summary>
        internal static string Exceptions_IO_FileNotFound {
            get {
                return ResourceManager.GetString("Exceptions_IO_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file was expected but not provided..
        /// </summary>
        internal static string Exceptions_IO_NoFileProfiled {
            get {
                return ResourceManager.GetString("Exceptions_IO_NoFileProfiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target file path of {x} was null or empty..
        /// </summary>
        internal static string Exceptions_IO_TargetFile_NullOrEmpty {
            get {
                return ResourceManager.GetString("Exceptions_IO_TargetFile_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Exceptions_Permisions_InvalidNumericNotation {
            get {
                return ResourceManager.GetString("Exceptions_Permisions_InvalidNumericNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Exceptions_Permissions_InvalidSymbolicNotation {
            get {
                return ResourceManager.GetString("Exceptions_Permissions_InvalidSymbolicNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {x} was deleted..
        /// </summary>
        internal static string IO_Directory_Deleted {
            get {
                return ResourceManager.GetString("IO_Directory_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {x}, which was empty, was deleted..
        /// </summary>
        internal static string IO_EmptyDirectory_Deleted {
            get {
                return ResourceManager.GetString("IO_EmptyDirectory_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {x} was deleted..
        /// </summary>
        internal static string IO_File_Deleted {
            get {
                return ResourceManager.GetString("IO_File_Deleted", resourceCulture);
            }
        }
    }
}
