//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlastairLundy.Extensions.IO.Internal.Localizations {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resyslib.IO.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Exceptions_IO_NoFileProfiled {
            get {
                return ResourceManager.GetString("Exceptions.IO.NoFileProfiled", resourceCulture);
            }
        }
        
        internal static string IO_File_Deleted {
            get {
                return ResourceManager.GetString("IO.File.Deleted", resourceCulture);
            }
        }
        
        internal static string IO_Directory_Deleted {
            get {
                return ResourceManager.GetString("IO.Directory.Deleted", resourceCulture);
            }
        }
        
        internal static string IO_EmptyDirectory_Deleted {
            get {
                return ResourceManager.GetString("IO.EmptyDirectory.Deleted", resourceCulture);
            }
        }
        
        internal static string Exceptions_Permissions_InvalidSymbolicNotation {
            get {
                return ResourceManager.GetString("Exceptions.Permissions.InvalidSymbolicNotation", resourceCulture);
            }
        }
        
        internal static string Exceptions_IO_FileNotFound {
            get {
                return ResourceManager.GetString("Exceptions.IO.FileNotFound", resourceCulture);
            }
        }
        
        internal static string Exceptions_Permisions_InvalidNumericNotation {
            get {
                return ResourceManager.GetString("Exceptions.Permisions.InvalidNumericNotation", resourceCulture);
            }
        }
        
        internal static string Exceptions_IO_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Exceptions.IO.DirectoryNotFound", resourceCulture);
            }
        }
    }
}
